(()=>{"use strict";
const $=id=>document.getElementById(id),currency=n=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(n||0),date=n=>n?new Date(n).toLocaleString():"—";
let role=null,selected=null,details=null,view="dashboard";
function message(text,bad=false){const box=$("adminMessage");box.textContent=text;box.className="admin-message"+(bad?" error":"");}
async function api(path,body){const options=body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{};const response=await fetch("/api/admin/"+path,{credentials:"same-origin",...options});const data=await response.json();if(!response.ok)throw Error(data.error||"Request failed");return data;}
function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=String(text);return el;}
function line(parent,key,value){const div=node("div");div.append(node("dt","",key),node("dd","",value));parent.append(div);}
function field(form,label,name,type="text",options){const wrap=node("label");wrap.textContent=label;let input;if(options){input=node("select");for(const [value,text] of options){const o=node("option","",text);o.value=value;input.append(o);}}else{input=node("input");input.type=type;}input.name=name;input.required=true;wrap.append(input);form.append(wrap);return input;}
function actionCard(parent,title,type,inputs,level=1,danger=false){if(({moderator:1,admin:2,owner:3})[role]<level)return;const card=node("div","admin-card"),heading=node("h2","",title),form=node("form");card.append(heading,form);for(const spec of inputs)spec(form);field(form,"Reason / audit note","reason");const button=node("button","",title);button.type="submit";if(danger)button.className="danger";form.append(button);form.addEventListener("submit",async event=>{event.preventDefault();if(!selected){message("Select a player first.",true);return;}const data=Object.fromEntries(new FormData(form));const body={actionId:crypto.randomUUID(),targetUserId:selected.id,type,reason:data.reason};for(const [key,value] of Object.entries(data)){if(key==="reason")continue;if(key==="amount"||key==="multiplier"||key==="durationMinutes")body[key]=Number(value);else body[key]=value;}if(type==="GRANT_MONEY")body.countTowardEarnings=form.elements.countTowardEarnings.checked;
if(type==="SET_ROLE")body.role=data.role||null;
if(type==="TIMEOUT"||type==="ADD_TEMP_BOOST"){if(data.expiresAtMs){body.expiresAtMs=Date.parse(data.expiresAtMs);delete body.durationMinutes;}else delete body.expiresAtMs;}if(type==="ADD_PERMANENT_BOOST")delete body.durationMinutes;
if(type==="RESET_PROGRESS"||type==="RESTORE_PROGRESS"){const expected=(type==="RESET_PROGRESS"?"RESET ":"RESTORE ")+selected.username;if(body.typedConfirmation!==expected){message("Type exactly: "+expected,true);return;}if(!confirm("Final confirmation: "+title+" for "+selected.username+" ("+selected.id+")?"))return;body.finalConfirm=true;}
if(type==="BAN"&&!confirm("Ban "+selected.username+" and revoke all their sessions?"))return;
button.disabled=true;try{await api("actions",body);message(title+" completed.");form.reset();await loadPlayer(selected.id);if(view==="audit")await loadAudit();}catch(error){message(error.message,true);}finally{button.disabled=false;}});parent.append(card);return form;}
const text=(label,name,type="text")=>form=>field(form,label,name,type);
const duration=form=>{field(form,"Duration","durationMinutes","select",[["10","10 minutes"],["30","30 minutes"],["60","1 hour"],["360","6 hours"],["1440","24 hours"],["10080","7 days"]]);const custom=field(form,"Custom expiry (optional)","expiresAtMs","datetime-local");custom.required=false;};
const kind=form=>field(form,"Boost type","kind","select",[["total","Total money"],["click","Click money"],["business","Business money"],["luck","Luck"]]);
function makeForms(){const mod=$("moderationForms"),boost=$("boostForms");mod.replaceChildren();boost.replaceChildren();const mg=node("div","admin-form-grid"),bg=node("div","admin-form-grid");mod.append(mg);boost.append(bg);
actionCard(mg,"Moderate username","MODERATE_USERNAME",[]);
actionCard(mg,"Temporary timeout","TIMEOUT",[duration]);actionCard(mg,"Remove timeout","REMOVE_TIMEOUT",[]);
const ban=actionCard(mg,"Permanent ban","BAN",[text("Internal note (optional)","note")],2,true);if(ban)ban.elements.note.required=false;actionCard(mg,"Unban","UNBAN",[],2);
const money=actionCard(bg,"Grant money","GRANT_MONEY",[text("Amount","amount","number")],2);if(money){const input=money.elements.amount;input.min="0.01";input.max="1e300";input.step="any";const label=node("label","admin-inline");const check=node("input");check.type="checkbox";check.name="countTowardEarnings";label.append(check,node("span","","Also count toward lifetime/run earnings"));money.insertBefore(label,money.elements.reason.parentElement);}
const temp=actionCard(bg,"Add temporary boost","ADD_TEMP_BOOST",[kind,text("Multiplier (1–100)","multiplier","number"),duration],2);if(temp){temp.elements.multiplier.min="1.01";temp.elements.multiplier.max="100";temp.elements.multiplier.step="0.01";}
const perm=actionCard(bg,"Add permanent boost","ADD_PERMANENT_BOOST",[kind,text("Multiplier (1–100)","multiplier","number")],3);if(perm){perm.elements.multiplier.min="1.01";perm.elements.multiplier.max="100";perm.elements.multiplier.step="0.01";}
actionCard(bg,"Remove boost","REMOVE_BOOST",[text("Boost ID from player details","boostId")],2);
const reset=actionCard(mg,"Reset player progress","RESET_PROGRESS",[text("Type RESET <username>","typedConfirmation")],3,true);if(reset){const warning=node("p","admin-warning","Reset clears gameplay progress. A full recovery snapshot is created first. Paid entitlements, account, roles and audit remain.");reset.prepend(warning);}
actionCard(mg,"Restore latest snapshot","RESTORE_PROGRESS",[text("Type RESTORE <username>","typedConfirmation")],3,true);
}
async function loadDashboard(){const data=await api("dashboard");const cards=$("dashboardCards");cards.replaceChildren();for(const [key,label] of [["players","Players"],["banned","Banned"],["suspended","Active timeouts"],["active_boosts","Active boosts"]]){const card=node("div","admin-card");card.append(node("span","",label),node("strong","",data[key]||0));cards.append(card);}}
async function search(q){const data=await api("players?q="+encodeURIComponent(q));const results=$("searchResults");results.replaceChildren();if(!data.players.length)results.append(node("p","","No players found."));for(const player of data.players){const button=node("button","admin-result",player.username);button.type="button";button.append(node("small","",player.id));button.addEventListener("click",()=>loadPlayer(player.id));results.append(button);}}
async function loadPlayer(id){const data=await api("players/"+encodeURIComponent(id));selected=data.player;details=data;const box=$("playerDetail");box.hidden=false;box.replaceChildren(node("h2","",data.player.username));const dl=node("dl");box.append(dl);line(dl,"User ID",data.player.id);line(dl,"Created",date(data.player.createdAtMs));line(dl,"Last seen",date(data.player.lastSeenAtMs));line(dl,"Moderation",data.moderation.status+(data.moderation.expiresAtMs?" until "+date(data.moderation.expiresAtMs):""));if(data.moderation.reason)line(dl,"Moderation reason",data.moderation.reason);const p=data.progress;if(p){for(const [key,label] of [["balance","Current cash"],["lifetimeCash","Lifetime cash"],["ratePerSecond","Money/sec"],["rebirths","Rebirths"],["empirePoints","Empire Points"],["totalClicks","Total clicks"],["totalPlaytime","Playtime (seconds)"]])line(dl,label,currency(p[key]));for(const [key,label] of [["businesses","Businesses"],["upgrades","Upgrades"],["boosterInventory","Booster inventory"],["equippedBoosters","Equipped boosters"]]){box.append(node("h3","",label),node("pre","",JSON.stringify(p[key],null,2)));}}else box.append(node("p","","No cloud progress yet."));box.append(node("h3","","Paid entitlements"),node("pre","",JSON.stringify(data.paidEntitlements,null,2)),node("h3","","Active admin boosts"));if(data.boosts.length)for(const b of data.boosts)box.append(node("p","",`${b.kind} ×${b.multiplier} · ${b.id} · ${b.expiresAtMs?date(b.expiresAtMs):"permanent"}`));else box.append(node("p","","None"));const warning=document.querySelector("#moderationForms .admin-warning");if(warning)warning.textContent="RESET WARNING · "+data.player.username+" · "+data.player.id+" · balance "+currency(p?.balance)+" · lifetime "+currency(p?.lifetimeCash)+" · rebirths "+currency(p?.rebirths)+" · playtime "+currency(p?.totalPlaytime)+" seconds. A recovery snapshot is created first; paid entitlements and account remain.";message("Selected "+data.player.username+" ("+data.player.id+").");}
async function loadAudit(){const data=await api("audit");const box=$("auditEntries");box.replaceChildren();for(const entry of data.entries){const card=node("div","audit-item");card.append(node("strong","",entry.type+" · "+date(entry.createdAtMs)),node("small","","By "+entry.actorUsername+" · Target "+(entry.targetUserId||"—")+" · "+entry.id),node("p","",entry.reason),node("pre","",JSON.stringify(entry.details)));box.append(card);}}
async function loadRoles(){const data=await api("roles"),box=$("roleEntries");box.replaceChildren();for(const r of data.roles)box.append(node("div","admin-result",r.username+" · "+r.role+" · "+r.user_id));const target=$("roleForm");target.replaceChildren();const form=actionCard(target,"Set selected player's role","SET_ROLE",[f=>field(f,"Role","role","select",[["moderator","Moderator"],["admin","Admin"],["","Remove role"]])],3);}
async function show(which){view=which;for(const button of document.querySelectorAll(".admin-tabs button"))button.classList.toggle("active",button.dataset.view===which);for(const section of document.querySelectorAll(".admin-section"))section.hidden=section.id!==which;try{if(which==="dashboard")await loadDashboard();if(which==="audit")await loadAudit();if(which==="roles")await loadRoles();}catch(error){message(error.message,true);}}
async function init(){try{const data=await api("me");role=data.role;$("adminApp").hidden=false;$("adminIdentity").textContent=role.toUpperCase();$("rolesTab").hidden=role!=="owner";makeForms();message("");document.querySelectorAll(".admin-tabs button").forEach(b=>b.addEventListener("click",()=>show(b.dataset.view)));$("searchForm").addEventListener("submit",async e=>{e.preventDefault();try{await search($("playerSearch").value);}catch(error){message(error.message,true);}});await show("dashboard");}catch(error){message("Admin access unavailable: "+error.message,true);}}
init();
})();
